import Tesseract from 'tesseract.js';
import { TextGeneration } from '@runanywhere/web-llamacpp';
import { type ExpenseCategory } from '../types/spendsense';

export interface ExtractedReceiptTransaction {
  date: string;
  merchant: string;
  amount: number;
  category: ExpenseCategory;
  confidence: number;
}

export interface ReceiptExtractionResult {
  transactions: ExtractedReceiptTransaction[];
  lowConfidence: boolean;
  rawText: string;
  parser: 'statement' | 'simple' | 'fallback';
}

interface OcrPreprocessResult {
  original: string;
  normalized: string;
  lines: string[];
}

interface ReceiptAnalysisOptions {
  llmReady?: boolean;
  modelStatus?: string;
}

interface SimpleReceiptLLMJson {
  merchant?: unknown;
  date?: unknown;
  amount?: unknown;
}

interface AmountHit {
  amount: number;
  index: number;
  raw: string;
}

const STATEMENT_TRIGGER_PATTERN = /transaction history/i;
const MONTH_DATE_PATTERN =
  /\b((?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s+\d{1,2}(?:,\s*\d{4})?)\b/gi;
const STATEMENT_DATE_PATTERN =
  /\b((?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s+\d{1,2}(?:,\s*\d{4})?)\b/i;
const STATEMENT_IGNORE_PATTERN =
  /(total spent|grand total|payment summary|generated by|date\s+description\s+amount)/i;
const TOTAL_LINE_PATTERN = /\b(grand\s*total|total\s*amount|amount\s*due|total)\b/i;
const IGNORE_AMOUNT_LINE_PATTERN = /\b(sub\s*total|subtotal|tax|gst|vat|cgst|sgst|discount)\b/i;
const NUMBER_PATTERN = /(?:inr|rs\.?)?\s*-?\d[\d,]*(?:\.\d{1,2})?/gi;
const NUMERIC_DATE_PATTERN = /\b(\d{4}[/-]\d{1,2}[/-]\d{1,2}|\d{1,2}[/-]\d{1,2}[/-]\d{2,4})\b/;

const devLog = (label: string, value: unknown) => {
  if (import.meta.env.DEV) {
    console.info(`[SpendSense][Receipt] ${label}`, value);
  }
};

const normalizeSpacing = (value: string): string => value.replace(/\s+/g, ' ').trim();

const preprocessOcrText = (rawText: string): OcrPreprocessResult => {
  const lines = rawText
    .split('\n')
    .map((line) => normalizeSpacing(line.replace(/[^\w\s.,:/\-()&]/g, ' ')))
    .filter(Boolean);

  return {
    original: rawText,
    normalized: lines.join('\n'),
    lines,
  };
};

const countStatementDates = (input: string): number => input.match(MONTH_DATE_PATTERN)?.length ?? 0;

const toAmount = (value: unknown): number | null => {
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  if (typeof value === 'string') {
    const parsed = Number(value.replace(/[^\d.-]/g, ''));
    return Number.isFinite(parsed) ? parsed : null;
  }
  return null;
};

const parseMonthDate = (value: string): string | null => {
  const match = value.match(
    /^(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]*\s+(\d{1,2})(?:,\s*(\d{4}))?$/i,
  );
  if (!match) return null;

  const monthMap: Record<string, number> = {
    jan: 0,
    feb: 1,
    mar: 2,
    apr: 3,
    may: 4,
    jun: 5,
    jul: 6,
    aug: 7,
    sep: 8,
    oct: 9,
    nov: 10,
    dec: 11,
  };
  const month = monthMap[match[1].slice(0, 3).toLowerCase()];
  const day = Number(match[2]);
  const year = match[3] ? Number(match[3]) : new Date().getFullYear();
  if (!Number.isFinite(day) || day < 1 || day > 31) return null;
  const parsed = new Date(year, month, day);
  if (Number.isNaN(parsed.getTime())) return null;
  return parsed.toISOString().slice(0, 10);
};

const toISODate = (value: string | null | undefined): string | null => {
  if (!value) return null;
  const cleaned = value.trim().replace(/\//g, '-');
  const direct = new Date(cleaned);
  if (!Number.isNaN(direct.getTime())) return direct.toISOString().slice(0, 10);

  const dmy = cleaned.match(/^(\d{1,2})-(\d{1,2})-(\d{2,4})$/);
  if (!dmy) return null;
  const [, dd, mm, yy] = dmy;
  const year = yy.length === 2 ? `20${yy}` : yy;
  const composed = new Date(`${year}-${mm.padStart(2, '0')}-${dd.padStart(2, '0')}`);
  if (Number.isNaN(composed.getTime())) return null;
  return composed.toISOString().slice(0, 10);
};

const fallbackCategory = (merchant: string): ExpenseCategory => {
  const source = merchant.toLowerCase();
  if (/rent|landlord|lease|electric|water|internet|bill|utility/.test(source)) return 'Bills';
  if (/grocery|fresh|mart|supermarket|food|restaurant|cafe/.test(source)) return 'Food';
  if (/uber|ola|metro|fuel|petrol|travel|taxi/.test(source)) return 'Travel';
  if (/movie|netflix|spotify|game|cinema/.test(source)) return 'Entertainment';
  if (/amazon|flipkart|shopping|mall|store/.test(source)) return 'Shopping';
  return 'Others';
};

const extractAmountHits = (line: string): AmountHit[] => {
  const hits: AmountHit[] = [];
  const matches = line.matchAll(NUMBER_PATTERN);
  for (const match of matches) {
    const raw = match[0] ?? '';
    const amount = toAmount(raw);
    const index = match.index ?? -1;
    if (amount === null || amount <= 0 || index < 0) continue;
    hits.push({ amount, index, raw });
  }
  return hits;
};

const extractLargestAmount = (lines: string[]): number | null => {
  const amounts = lines.flatMap((line) => extractAmountHits(line).map((hit) => hit.amount));
  if (amounts.length === 0) return null;
  return Math.max(...amounts);
};

const extractAmountNearTotal = (lines: string[]): number | null => {
  for (const line of lines) {
    if (!TOTAL_LINE_PATTERN.test(line) || IGNORE_AMOUNT_LINE_PATTERN.test(line)) continue;
    const hits = extractAmountHits(line);
    if (hits.length > 0) return hits[hits.length - 1].amount;
  }
  return extractLargestAmount(lines);
};

const extractFirstUppercaseLine = (lines: string[]): string | null => {
  for (const line of lines) {
    if (line.length < 3) continue;
    if (STATEMENT_IGNORE_PATTERN.test(line)) continue;
    const alphaOnly = line.replace(/[^A-Za-z]/g, '');
    if (!alphaOnly) continue;
    const uppercaseRatio = alphaOnly.replace(/[A-Z]/g, '').length / alphaOnly.length;
    if (uppercaseRatio < 0.25) return line;
  }
  return null;
};

const extractAnyDate = (lines: string[]): string | null => {
  for (const line of lines) {
    const month = line.match(STATEMENT_DATE_PATTERN);
    if (month) {
      const parsed = parseMonthDate(month[1]);
      if (parsed) return parsed;
    }
    const numeric = line.match(NUMERIC_DATE_PATTERN);
    if (numeric) {
      const parsed = toISODate(numeric[1]);
      if (parsed) return parsed;
    }
  }
  return null;
};

const statementTransactionsFromOCR = (processed: OcrPreprocessResult): ExtractedReceiptTransaction[] => {
  const rows: ExtractedReceiptTransaction[] = [];

  for (const rawLine of processed.lines) {
    if (STATEMENT_IGNORE_PATTERN.test(rawLine)) continue;

    const dateMatch = rawLine.match(STATEMENT_DATE_PATTERN);
    if (!dateMatch) continue;
    const date = parseMonthDate(dateMatch[1]);
    if (!date) continue;

    const amountHits = extractAmountHits(rawLine);
    if (amountHits.length === 0) continue;
    const lastAmount = amountHits[amountHits.length - 1];

    const dateStart = rawLine.indexOf(dateMatch[0]);
    if (dateStart < 0 || lastAmount.index <= dateStart) continue;

    const merchant = normalizeSpacing(
      rawLine.slice(dateStart + dateMatch[0].length, lastAmount.index),
    );
    if (!merchant || STATEMENT_IGNORE_PATTERN.test(merchant)) continue;

    rows.push({
      date,
      merchant,
      amount: lastAmount.amount,
      category: fallbackCategory(merchant),
      confidence: 0.95,
    });
  }

  return rows;
};

const extractFirstJsonObject = (text: string): string | null => {
  const start = text.indexOf('{');
  if (start < 0) return null;
  let depth = 0;
  for (let i = start; i < text.length; i += 1) {
    if (text[i] === '{') depth += 1;
    if (text[i] === '}') depth -= 1;
    if (depth === 0) return text.slice(start, i + 1);
  }
  return null;
};

const parseSimpleLLMJson = (raw: string): SimpleReceiptLLMJson | null => {
  const cleaned = raw.replace(/```json/gi, '').replace(/```/g, '').trim();
  const objectOnly = extractFirstJsonObject(cleaned) ?? cleaned;
  const safeJson = objectOnly.replace(/,\s*([}\]])/g, '$1');
  try {
    const parsed = JSON.parse(safeJson) as SimpleReceiptLLMJson;
    return parsed && typeof parsed === 'object' ? parsed : null;
  } catch {
    return null;
  }
};

const buildFallbackTransaction = (processed: OcrPreprocessResult): ExtractedReceiptTransaction => {
  const merchant = extractFirstUppercaseLine(processed.lines) ?? 'Unknown Merchant';
  const amount = extractLargestAmount(processed.lines) ?? 0;
  const date = extractAnyDate(processed.lines) ?? new Date().toISOString().slice(0, 10);

  return {
    date,
    merchant,
    amount,
    category: fallbackCategory(merchant),
    confidence: 0.35,
  };
};

const simpleReceiptFromLLM = async (
  processed: OcrPreprocessResult,
  amountHint: number,
): Promise<ExtractedReceiptTransaction | null> => {
  const prompt = [
    'Extract receipt fields from OCR text and return strict JSON only.',
    'No markdown. No extra text. No trailing commas.',
    'Output schema:',
    '{"merchant":"string","date":"YYYY-MM-DD","amount":number}',
    'Use the OCR text and amount hint.',
    `AMOUNT_HINT=${amountHint}`,
    `OCR_TEXT:\n${processed.normalized.slice(0, 5000)}`,
  ].join('\n');

  const response = await TextGeneration.generate(prompt, {
    maxTokens: 180,
    temperature: 0,
    topP: 0.9,
  });
  const payload = parseSimpleLLMJson(response.text ?? '');
  if (!payload) return null;

  const merchantRaw = typeof payload.merchant === 'string' ? normalizeSpacing(payload.merchant) : '';
  const merchant = merchantRaw || extractFirstUppercaseLine(processed.lines) || 'Unknown Merchant';
  const amount = toAmount(payload.amount) ?? amountHint;
  const date = toISODate(typeof payload.date === 'string' ? payload.date : '') ?? extractAnyDate(processed.lines) ?? new Date().toISOString().slice(0, 10);

  return {
    merchant,
    amount: amount > 0 ? amount : amountHint,
    date,
    category: fallbackCategory(merchant),
    confidence: 0.8,
  };
};

export async function extractTextFromReceipt(
  imageFile: File,
  onProgress?: (value: number, status: string) => void,
): Promise<string> {
  const worker = await Tesseract.createWorker('eng', 1, {
    logger: (message) => {
      if (onProgress) onProgress(message.progress ?? 0, message.status ?? 'processing');
    },
    cacheMethod: 'write',
  });

  try {
    const { data } = await worker.recognize(imageFile);
    const text = (data.text ?? '').trim();
    if (!text) throw new Error('No readable text found in receipt image.');
    return text;
  } finally {
    await worker.terminate();
  }
}

export async function analyzeReceiptLocally(
  imageFile: File,
  onOcrProgress?: (value: number, status: string) => void,
  onStageChange?: (stage: 'scanning' | 'analyzing') => void,
  options: ReceiptAnalysisOptions = {},
): Promise<ReceiptExtractionResult> {
  onStageChange?.('scanning');
  const rawText = await extractTextFromReceipt(imageFile, onOcrProgress);
  const processed = preprocessOcrText(rawText);
  devLog('OCR text', rawText);

  const isStatement =
    STATEMENT_TRIGGER_PATTERN.test(processed.normalized) ||
    countStatementDates(processed.original) > 3;
  if (isStatement) {
    const statementRows = statementTransactionsFromOCR(processed);
    if (statementRows.length > 0) {
      return {
        transactions: statementRows,
        lowConfidence: false,
        rawText,
        parser: 'statement',
      };
    }
  }

  onStageChange?.('analyzing');
  const amountHint = extractAmountNearTotal(processed.lines) ?? extractLargestAmount(processed.lines) ?? 0;

  if (options.llmReady) {
    try {
      const simple = await simpleReceiptFromLLM(processed, amountHint);
      if (simple) {
        return {
          transactions: [simple],
          lowConfidence: simple.confidence < 0.85,
          rawText,
          parser: 'simple',
        };
      }
    } catch (error) {
      console.warn('[SpendSense][Receipt] simple-mode LLM failed, using fallback mode', {
        error,
        modelStatus: options.modelStatus ?? 'unknown',
      });
    }
  } else {
    console.info('[SpendSense][Receipt] model unavailable, skipping LLM', {
      modelStatus: options.modelStatus ?? 'unknown',
    });
  }

  const fallback = buildFallbackTransaction(processed);
  return {
    transactions: [fallback],
    lowConfidence: true,
    rawText,
    parser: 'fallback',
  };
}
